# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobSchd', '0047_auto_20181130_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobfinal',
            old_name='synthesize',
            new_name='synthesize2',
        ),
    ]
