project:
    #To generate a synthetic population
  synthesize: true
  name: PACOG
    #File location
  location: home/sumit/Desktop/Popgen-processing/ready/PACOG
    #Setup input data with given forms
  inputs:
    entities: [household, groupquarter, person]
    housing_entities: [household, groupquarter]
    person_entities: [person]
    column_names:
      hid: hid
      pid: pid
      geo: geo
      region: region
      sample_geo: sample_geo
    location:
      geo_corr_mapping:
        geo_to_sample: geo_sample_mapping.csv
        region_to_sample: region_sample_mapping.csv
        region_to_geo: region_geo_mapping.csv
      sample:
        household: household_sample.csv
        person: person_sample.csv
        groupquarter: groupquarters_sample.csv
      marginals:
        geo:
          household: household_marginals.csv
          person: person_marginals.csv
          groupquarter: groupquarters_marginals.csv
        region:
          household: region_household_marginals.csv
          person: region_person_marginals.csv
          groupquarter: region_groupquarters_marginals.csv
    #Start to provide scenario
  scenario:
    #Brief description
  - description: CDOT-PACOG TAZ Scenario
    #If control variables are applied in multi-environment (geo and region), true
    apply_region_controls: true
    #Based on input setting, write down header name for each value
    control_variables:
      region:
        household: [hhldrtype,hhldsize,hhldrage]
        groupquarter: [groupquarter]
        person: [employment,agep,gender]
      geo:
        household: [tazinc]
        groupquarter: [groupquarter_dummy]
        person: [totpop]
    #Setting for IPF procedure, reweighting, and drawing household samples
    parameters:
      ipf:
        tolerance: 0.0001
        iterations: 250
        zero_marginal_correction: 0.00001
        rounding_procedure: bucket
        archive_performance_frequency: 1
    #Select either IPU or Entropy
      reweighting:
        procedure: ipu
        tolerance: 0.0001
        inner_iterations: 1
        outer_iterations: 50
        archive_performance_frequency: 1
      draws:
        pvalue_tolerance: 0.9999
        iterations: 25
        seed: 0 

    geos_to_synthesize:
      region:
         #Leave empty blank if we synthesize specific region, then use ID
        ids: [101]
        all_ids: true
      geo:
        ids: [5144,5145,5146,5147,5148,5149,5150,5151,5152,5153,5154,5155,5156,5157,5158,5159,5160,5161,5162,5163,5164,5165,5166,5167,5168,5169,5170,5171,5172,5173,5174,5175,5176,5177,5178,5179,5180,5181,5182,5183,5184,5185,5186,5187,5188,5189,5190,5191,5192,5193,5194,5195,5196,5197,5198,5199,5200,5201,5202,5203,5204,5205,5206,5207,5208,5209,5210,5211,5212,5213,5214,5215,5216,5217,5218,5219,5220,5221,5222,5223,5224,5225,5226,5227,5228,5229,5230,5231,5232,5233,5234,5235,5236,5237,5238,5239,5240,5241,5242,5243,5244,5245,5246,5247,5248,5249,5250,5251,5252,5253,5254,5255,5256,5257,5258,5259,5260,5261,5262,5263,5264,5265,5266,5267,5268,5269,5270,5271,5272,5273,5274,5275,5276,5277,5278,5279,5280,5281,5282,5283,5284,5285,5286,5287,5288,5289,5290,5291,5292,5293,5294,5295,5296,5297,5298,5299,5300,5301,5302,5303,5304,5305,5306,5307,5308,5309,5310,5311,5312,5313,5314,5315,5316,5317,5318,5319,5320,5321,5322,5323,5324,5325,5326,5327,5328,5329,5330,5331,5332,5333,5334,5335,5336,5337,5338,5339,5340,5341,5342,5343,5344,5345,5346,5347,5348,5349]
        all_ids: true

    outputs:
      performance: [ipf, reweighting, drawing]
      weights:
        export: true
        collate_across_geos: false
      multiway:
      - variables: [hhldrtype, hhldrage]
        filename: hhldrtype_hhldrage.csv
        filetype: csv
        entity: household
      - variables: [agep, gender]
        filename: agep_gender.csv
        filetype: csv
        entity: person

      summary:
        region:
          filename: summary_region.csv
          filetype: csv
        geo:
          filename: summary_geo.csv
          filetype: csv
      synthetic_population:
        housing:
          filename: housing_synthetic.csv
          filetype: csv
        person:
          filename: person_synthetic.csv
          filetype: csv
