project:
    #To generate a synthetic population
  synthesize: true
  name: Colorado_DRCOG
    #File location
  location: home/sumit/Desktop/Popgen-processing/ready/Colorado_DRCOG
    #Setup input data with given forms
  inputs:
    entities: [household, groupquarter, person]
    housing_entities: [household, groupquarter]
    person_entities: [person]
    column_names:
      hid: hid
      pid: pid
      geo: geo
      region: region
      sample_geo: sample_geo
    location:
      geo_corr_mapping:
        geo_to_sample: geo_sample_mapping.csv
        region_to_sample: region_sample_mapping.csv
        region_to_geo: region_geo_mapping.csv
      sample:
        household: household_sample.csv
        person: person_sample.csv
        groupquarter: groupquarters_sample.csv
      marginals:
        geo:
          household: household_marginals.csv
          person: person_marginals.csv
          groupquarter: groupquarters_marginals.csv
        region:
          household: region_household_marginals.csv
          person: region_person_marginals.csv
          groupquarter: region_groupquarters_marginals.csv
    #Start to provide scenario
  scenario:
    #Brief description
  - description: CDOT-DRCOG TAZ Scenario
    #If control variables are applied in multi-environment (geo and region), true
    apply_region_controls: true
    #Based on input setting, write down header name for each value
    control_variables:
      region:
        household: [hhldrtype,hhldsize,hhldrage]
        groupquarter: [groupquarter]
        person: [employment,agep,gender]
      geo:
        household: [tazinc]
        groupquarter: [groupquarter_dummy]
        person: [totpop]
    #Setting for IPF procedure, reweighting, and drawing household samples
    parameters:
      ipf:
        tolerance: 0.0001
        iterations: 250
        zero_marginal_correction: 0.00001
        rounding_procedure: bucket
        archive_performance_frequency: 1
    #Select either IPU or Entropy
      reweighting:
        procedure: ipu
        tolerance: 0.0001
        inner_iterations: 1
        outer_iterations: 50
        archive_performance_frequency: 1
      draws:
        pvalue_tolerance: 0.9999
        iterations: 25
        seed: 0 

    geos_to_synthesize:
      region:
         #Leave empty blank if we synthesize specific region, then use ID
        ids: [1,5,13,14,19,31,35,39,47,59,123]
        all_ids: true
      geo:
        ids: []
        all_ids: true

    outputs:
      performance: [ipf, reweighting, drawing]
      weights:
        export: true
        collate_across_geos: false
      multiway:
      - variables: [hhldrtype, hhldrage]
        filename: hhldrtype_hhldrage.csv
        filetype: csv
        entity: household
      - variables: [agep, gender]
        filename: agep_gender.csv
        filetype: csv
        entity: person

      summary:
        region:
          filename: summary_region.csv
          filetype: csv
        geo:
          filename: summary_geo.csv
          filetype: csv
      synthetic_population:
        housing:
          filename: housing_synthetic.csv
          filetype: csv
        person:
          filename: person_synthetic.csv
          filetype: csv
