project:
    #To generate a synthetic population
  synthesize: true
  name: Conneticut_Run
    #File location
  location: home/sumit/Desktop/Popgen-processing/ready/Conneticut_Run
    #Setup input data with given forms
  inputs:
    entities: [household, groupquarter, person]
    housing_entities: [household, groupquarter]
    person_entities: [person]
    column_names:
      hid: hid
      pid: pid
      geo: geo
      region: region
      sample_geo: geo
    location:
      geo_corr_mapping:
        geo_to_sample: FINAL.xlsx
        region_to_sample: 986b61470b193b1013456379d68d9209_GWonY0J.jpg
        region_to_geo: FINAL2.xlsx
      sample:
        household: FINAL_riLa4X2.xlsx
        person: FINAL2_4QVEsmx.xlsx
        groupquarter: FINAL_6QHVBH2.xlsx
      marginals:
        geo:
          household: Sponsoring_cmte_members_for_abstract_reviews.xlsx
          person: FINAL_pUCsULM.xlsx
          groupquarter: 2016_attendees-v2.xlsx
        region:
          household: FINAL2_8Z0Z4HK.xlsx
          person: FINAL2_1gNnu7Q.xlsx
          groupquarter: FINAL_d4Vwufn.xlsx
    #Start to provide scenario
  scenario:
    #Brief description
  - description: Connecticut TAZ Scenario
    #If control variables are applied in multi-environment (geo and region), true
    apply_region_controls: true
    #Based on input setting, write down header name for each value
    control_variables:
      region:
        household: [hhrtotals]
        groupquarter: [gqrtotals]
        person: [rpsex, rpage, rpworker, prtotals]
      geo:
        household: [hhtotals, hinc, hsize]
        groupquarter: [gqtotals, gqtype]
        person: [pworker, ptotals]
    #Setting for IPF procedure, reweighting, and drawing household samples
    parameters:
      ipf:
        tolerance: 0.0001
        iterations: 1
        zero_marginal_correction: 0.00001
        rounding_procedure: bucket
        archive_performance_frequency: 1
    #Select either IPU or Entropy
      reweighting:
        procedure: IPU
        tolerance: 0.0001
        inner_iterations: 1
        outer_iterations: 1000
        archive_performance_frequency: 1
      draws:
        pvalue_tolerance: 0.9999
        iterations: 1
        seed: 0 

    geos_to_synthesize:
      region:
         #Leave empty blank if we synthesize specific region, then use ID
        ids: [1,2,3]
        all_ids: true
      geo:
        ids: [1,2,3]
        all_ids: true

    outputs:
      performance: [ipf, reweighting, drawing]
      weights:
        export: true
        collate_across_geos: false
      multiway:
      - variables: [hsize, hinc]
        filename: hhsize_income.csv
        filetype: csv
        entity: person
      - variables: [hsize, hinc]
        filename: hhsize_income.csv
        filetype: csv
        entity: person

      summary:
        region:
          filename: summary_region.csv
          filetype: csv
        geo:
          filename: summary_geo.csv
          filetype: csv
      synthetic_population:
        housing:
          filename: housing_synthetic.csv
          filetype: csv
        person:
          filename: person_synthetic.csv
          filetype: csv
